# Generated by Django 5.2.16 on 2026-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter')], default='student', max_length=20),
        ),
    ]
