# Generated by Django 5.2.16 on 2026-07-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_recruiterprofile_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
