# Generated by Django 5.2.16 on 2026-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_recruiterprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
