# Generated by Django 5.2.16 on 2026-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_studentprofile_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expected_graduation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
