# Generated by Django 5.2.16 on 2026-07-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='organization',
            new_name='organisation',
        ),
    ]
