# Generated by Django 5.2.16 on 2026-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_deadlinereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
